"use server"

import fs from 'fs';
import path from 'path';
import { db } from '../../lib/db';

export type TimeRange = 'short_term' | 'medium_term' | 'long_term';

export interface SpotifyItem {
  id: string;
  name: string;
  artist?: string;
  imageUrl: string;
}

// Ensure the image_cache table exists
db.exec(`
  CREATE TABLE IF NOT EXISTS image_cache (
    id TEXT PRIMARY KEY,
    image_url TEXT,
    object_type TEXT
  )
`);

function getCachedImage(id: string): string | null {
  const row = db.prepare('SELECT image_url FROM image_cache WHERE id = ?').get(id) as any;
  return row ? row.image_url : null;
}

function setCachedImage(id: string, url: string, type: string) {
  if (!url) return;
  db.prepare('INSERT OR REPLACE INTO image_cache (id, image_url, object_type) VALUES (?, ?, ?)')
    .run(id, url, type);
}

// Read the cached access token generated by the Python spotipy script
function getAccessToken(): string | null {
  try {
    const cachePath = path.resolve(process.cwd(), '../.spotipy_cache');
    if (fs.existsSync(cachePath)) {
      const content = fs.readFileSync(cachePath, 'utf8');
      const cache = JSON.parse(content);
      return cache.access_token || null;
    }
    return null;
  } catch (error) {
    console.error("Could not read .spotipy_cache", error);
    return null;
  }
}

// Fetch with retry + exponential backoff for Spotify 429 rate limits
async function fetchWithRetry(url: string, token: string, maxRetries = 3): Promise<Response | null> {
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const res = await fetch(url, {
        cache: 'no-store',
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.status === 429) {
        const retryAfter = parseInt(res.headers.get('Retry-After') || '1', 10);
        const waitMs = Math.max(retryAfter * 1000, 1000 * Math.pow(2, attempt));
        console.warn(`[Spotify 429] Rate limited on attempt ${attempt + 1}. Waiting ${waitMs}ms...`);
        await new Promise(resolve => setTimeout(resolve, waitMs));
        continue;
      }
      return res;
    } catch (e) {
      if (attempt === maxRetries) {
        console.error(`[Spotify] Fetch failed after ${maxRetries + 1} attempts:`, e);
        return null;
      }
      await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, attempt)));
    }
  }
  return null;
}

function getDateThreshold(timeRange: TimeRange): string {
  const d = new Date();
  if (timeRange === 'short_term') {
    d.setMonth(d.getMonth() - 1); // 4 Weeks
  } else if (timeRange === 'medium_term') {
    d.setMonth(d.getMonth() - 6); // 6 Months
  } else {
    d.setFullYear(d.getFullYear() - 20); // All time
  }
  return d.toISOString();
}

// Helper: fetch artist image with retry
async function fetchArtistImage(name: string, token: string): Promise<string> {
  // Strict search
  const res = await fetchWithRetry(
    `https://api.spotify.com/v1/search?q=artist:${encodeURIComponent(name)}&type=artist&limit=1`,
    token
  );
  if (res?.ok) {
    const data = await res.json();
    const item = data.artists?.items?.[0];
    if (item?.images?.length) {
      return item.images.length > 1 ? item.images[1].url : item.images[0].url;
    }
  }
  // Fallback: plain text search
  const fallback = await fetchWithRetry(
    `https://api.spotify.com/v1/search?q=${encodeURIComponent(name)}&type=artist&limit=1`,
    token
  );
  if (fallback?.ok) {
    const data = await fallback.json();
    const item = data.artists?.items?.[0];
    if (item?.images?.length) {
      return item.images.length > 1 ? item.images[1].url : item.images[0].url;
    }
  }
  return '';
}

// Helper: fetch track image with retry
async function fetchTrackImage(trackId: string, name: string, artist: string, token: string): Promise<string> {
  // Direct track lookup
  const res = await fetchWithRetry(
    `https://api.spotify.com/v1/tracks/${trackId}`,
    token
  );
  if (res?.ok) {
    const data = await res.json();
    if (data.album?.images?.length) {
      return data.album.images.length > 1 ? data.album.images[1].url : data.album.images[0].url;
    }
  }
  // Fallback: search
  const q = encodeURIComponent(`track:${name} artist:${artist}`);
  const searchRes = await fetchWithRetry(
    `https://api.spotify.com/v1/search?q=${q}&type=track&limit=1`,
    token
  );
  if (searchRes?.ok) {
    const data = await searchRes.json();
    const found = data.tracks?.items?.[0];
    if (found?.album?.images?.length) {
      return found.album.images.length > 1 ? found.album.images[1].url : found.album.images[0].url;
    }
  }
  return '';
}

// Helper: fetch album image with retry
async function fetchAlbumImage(albumName: string, artist: string, token: string): Promise<string> {
  // Strict search
  const q = encodeURIComponent(`album:${albumName} artist:${artist}`);
  const res = await fetchWithRetry(
    `https://api.spotify.com/v1/search?q=${q}&type=album&limit=1`,
    token
  );
  if (res?.ok) {
    const data = await res.json();
    const item = data.albums?.items?.[0];
    if (item?.images?.length) {
      return item.images.length > 1 ? item.images[1].url : item.images[0].url;
    }
  }
  // Fallback: plain text
  const fallback = await fetchWithRetry(
    `https://api.spotify.com/v1/search?q=${encodeURIComponent(albumName)}&type=album&limit=1`,
    token
  );
  if (fallback?.ok) {
    const data = await fallback.json();
    const item = data.albums?.items?.[0];
    if (item?.images?.length) {
      return item.images.length > 1 ? item.images[1].url : item.images[0].url;
    }
  }
  return '';
}

export async function getTopArtists(timeRange: TimeRange = 'short_term'): Promise<SpotifyItem[]> {
  const token = getAccessToken();
  const dateThreshold = getDateThreshold(timeRange);

  const topLocalArtists = db.prepare(`
    SELECT t.artist_name as name, CAST(SUM(s.ms_played) AS INTEGER) as total_ms
    FROM streaming_history s
    JOIN tracks t ON s.track_uri = t.track_uri
    WHERE s.played_at >= ?
    GROUP BY t.artist_name
    ORDER BY total_ms DESC
    LIMIT 10
  `).all(dateThreshold) as { name: string; total_ms: number }[];

  const enrichedArtists = await Promise.all(
    topLocalArtists.map(async (row) => {
      const cacheKey = `artist:${row.name}`;
      let imageUrl = getCachedImage(cacheKey) || '';

      if (!imageUrl && token) {
        imageUrl = await fetchArtistImage(row.name, token);
        if (imageUrl) {
          setCachedImage(cacheKey, imageUrl, 'artist');
        }
      }

      return {
        id: `artist-${row.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
        name: row.name,
        imageUrl
      };
    })
  );

  return enrichedArtists;
}

export async function getTopTracks(timeRange: TimeRange = 'short_term'): Promise<SpotifyItem[]> {
  const token = getAccessToken();
  const dateThreshold = getDateThreshold(timeRange);

  const topLocalTracks = db.prepare(`
    SELECT t.track_name as name, t.artist_name as artist, t.track_uri as uri, CAST(SUM(s.ms_played) AS INTEGER) as total_ms
    FROM streaming_history s
    JOIN tracks t ON s.track_uri = t.track_uri
    WHERE s.played_at >= ?
    GROUP BY t.track_uri
    ORDER BY total_ms DESC
    LIMIT 10
  `).all(dateThreshold) as { name: string; artist: string; uri: string; total_ms: number }[];

  const enrichedTracks = await Promise.all(
    topLocalTracks.map(async (row, index) => {
      const trackId = row.uri?.split(':').pop();
      const cacheKey = `track:${trackId || row.name + row.artist}`;
      let imageUrl = getCachedImage(cacheKey) || '';

      if (!imageUrl && token && trackId) {
        imageUrl = await fetchTrackImage(trackId, row.name, row.artist, token);
        if (imageUrl) {
          setCachedImage(cacheKey, imageUrl, 'track');
        }
      }

      return {
        id: trackId || `local-track-${index}`,
        name: row.name,
        artist: row.artist,
        imageUrl
      };
    })
  );

  return enrichedTracks;
}

export async function getTopAlbums(timeRange: TimeRange = 'short_term'): Promise<SpotifyItem[]> {
  const token = getAccessToken();
  const dateThreshold = getDateThreshold(timeRange);

  const topLocalAlbums = db.prepare(`
    SELECT t.album_name as name, t.artist_name as artist, CAST(SUM(s.ms_played) AS INTEGER) as total_ms
    FROM streaming_history s
    JOIN tracks t ON s.track_uri = t.track_uri
    WHERE s.played_at >= ?
      AND t.album_name IS NOT NULL
      AND t.album_name != 'Unknown Album'
      AND t.album_name != ''
    GROUP BY t.album_name
    ORDER BY total_ms DESC
    LIMIT 10
  `).all(dateThreshold) as { name: string; artist: string; total_ms: number }[];

  const enrichedAlbums = await Promise.all(
    topLocalAlbums.map(async (row) => {
      const cacheKey = `album:${row.name}:${row.artist}`;
      let imageUrl = getCachedImage(cacheKey) || '';

      if (!imageUrl && token) {
        imageUrl = await fetchAlbumImage(row.name, row.artist, token);
        if (imageUrl) {
          setCachedImage(cacheKey, imageUrl, 'album');
        }
      }

      return {
        id: `album-${row.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
        name: row.name,
        artist: row.artist,
        imageUrl
      };
    })
  );

  return enrichedAlbums;
}

export interface RecentTrack {
  id: string;
  track_name: string;
  artist_name: string;
  played_at: string;
  imageUrl: string;
}

export async function getRecentlyPlayed(limit = 5): Promise<RecentTrack[]> {
  const token = getAccessToken();

  const recentRows = db.prepare(`
    SELECT t.track_name, t.artist_name, t.track_uri, s.played_at
    FROM streaming_history s
    JOIN tracks t ON s.track_uri = t.track_uri
    ORDER BY s.played_at DESC
    LIMIT ?
  `).all(limit) as { track_name: string; artist_name: string; track_uri: string; played_at: string }[];

  const enriched = await Promise.all(
    recentRows.map(async (row, index) => {
      const trackId = row.track_uri?.split(':').pop();
      const cacheKey = `track:${trackId || row.track_name + row.artist_name}`;
      let imageUrl = getCachedImage(cacheKey) || '';

      if (!imageUrl && token && trackId) {
        imageUrl = await fetchTrackImage(trackId, row.track_name, row.artist_name, token);
        if (imageUrl) {
          setCachedImage(cacheKey, imageUrl, 'track');
        }
      }

      return {
        id: `recent-${index}-${trackId || row.track_name}`,
        track_name: row.track_name,
        artist_name: row.artist_name,
        played_at: row.played_at,
        imageUrl
      };
    })
  );

  return enriched;
}

export async function getLastPlayedTrack(): Promise<RecentTrack | null> {
  const tracks = await getRecentlyPlayed(1);
  return tracks.length > 0 ? tracks[0] : null;
}
